# .github/workflows/pages.yml (예시)
- name: Build
  run: npm run build
- name: Copy 404 for SPA
  run: cp dist/index.html dist/404.html
- name: Upload artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: ./dist